"""Layout pattern definitions — 6 dashboard layout types."""

LAYOUTS = [
    {
        "id": "sidebar-stack",
        "name": "Sidebar Stack",
        "description": "Persistent left nav, KPI strip at top, stacked content blocks.",
        "columns": 5,
        "slots": [
            {"id": "nav", "row": 1, "col": 1, "rowSpan": 4, "colSpan": 1},
            {"id": "kpi", "row": 1, "col": 2, "rowSpan": 1, "colSpan": 4},
            {"id": "main-chart", "row": 2, "col": 2, "rowSpan": 1, "colSpan": 4},
            {"id": "row3", "row": 3, "col": 2, "rowSpan": 1, "colSpan": 4},
            {"id": "row4", "row": 4, "col": 2, "rowSpan": 1, "colSpan": 4},
        ],
    },
    {
        "id": "bento-grid",
        "name": "Bento Grid",
        "description": "Mixed card sizes for modular, prioritized layout.",
        "columns": 4,
        "slots": [
            {"id": "hero", "row": 1, "col": 1, "rowSpan": 1, "colSpan": 2},
            {"id": "side1", "row": 1, "col": 3, "rowSpan": 1, "colSpan": 1},
            {"id": "side2", "row": 1, "col": 4, "rowSpan": 1, "colSpan": 1},
            {"id": "wide1", "row": 2, "col": 1, "rowSpan": 1, "colSpan": 1},
            {"id": "wide2", "row": 2, "col": 2, "rowSpan": 1, "colSpan": 1},
            {"id": "wide3", "row": 2, "col": 3, "rowSpan": 1, "colSpan": 1},
            {"id": "wide4", "row": 2, "col": 4, "rowSpan": 1, "colSpan": 1},
            {"id": "row3a", "row": 3, "col": 1, "rowSpan": 1, "colSpan": 1},
            {"id": "row3b", "row": 3, "col": 2, "rowSpan": 1, "colSpan": 1},
            {"id": "row3c", "row": 3, "col": 3, "rowSpan": 1, "colSpan": 1},
            {"id": "row3d", "row": 3, "col": 4, "rowSpan": 1, "colSpan": 1},
            {"id": "footer", "row": 4, "col": 1, "rowSpan": 1, "colSpan": 4},
        ],
    },
    {
        "id": "center-spotlight",
        "name": "Center Spotlight",
        "description": "One dominant live panel, side rails for supporting stats.",
        "columns": 5,
        "slots": [
            {"id": "header", "row": 1, "col": 1, "rowSpan": 1, "colSpan": 5},
            {"id": "left", "row": 2, "col": 1, "rowSpan": 2, "colSpan": 1},
            {"id": "stage", "row": 2, "col": 2, "rowSpan": 2, "colSpan": 3},
            {"id": "right", "row": 2, "col": 5, "rowSpan": 2, "colSpan": 1},
            {"id": "bottom", "row": 4, "col": 1, "rowSpan": 1, "colSpan": 5},
        ],
    },
    {
        "id": "tabbed-workspace",
        "name": "Tabbed Workspace",
        "description": "Category tabs, each with its own canvas.",
        "columns": 4,
        "slots": [
            {"id": "toolbar", "row": 1, "col": 1, "rowSpan": 1, "colSpan": 4},
            {"id": "tabs", "row": 2, "col": 1, "rowSpan": 1, "colSpan": 4},
            {"id": "ws1", "row": 3, "col": 1, "rowSpan": 1, "colSpan": 1},
            {"id": "ws2", "row": 3, "col": 2, "rowSpan": 1, "colSpan": 1},
            {"id": "ws3", "row": 3, "col": 3, "rowSpan": 1, "colSpan": 1},
            {"id": "ws4", "row": 4, "col": 1, "rowSpan": 1, "colSpan": 4},
        ],
    },
    {
        "id": "timeline-board",
        "name": "Timeline Board",
        "description": "Center event stream, side context, footer stats.",
        "columns": 5,
        "slots": [
            {"id": "header", "row": 1, "col": 1, "rowSpan": 1, "colSpan": 5},
            {"id": "left", "row": 2, "col": 1, "rowSpan": 2, "colSpan": 1},
            {"id": "center", "row": 2, "col": 2, "rowSpan": 2, "colSpan": 3},
            {"id": "right", "row": 2, "col": 5, "rowSpan": 2, "colSpan": 1},
            {"id": "footer", "row": 4, "col": 1, "rowSpan": 1, "colSpan": 5},
        ],
    },
    {
        "id": "two-column",
        "name": "Two-Column Command",
        "description": "Wide analysis column + narrow support rail.",
        "columns": 4,
        "slots": [
            {"id": "header", "row": 1, "col": 1, "rowSpan": 1, "colSpan": 4},
            {"id": "kpi-row", "row": 2, "col": 1, "rowSpan": 1, "colSpan": 3},
            {"id": "main-chart", "row": 3, "col": 1, "rowSpan": 1, "colSpan": 3},
            {"id": "main-row1", "row": 4, "col": 1, "rowSpan": 1, "colSpan": 3},
            {"id": "main-row2", "row": 5, "col": 1, "rowSpan": 1, "colSpan": 3},
            {"id": "rail1", "row": 2, "col": 4, "rowSpan": 1, "colSpan": 1},
            {"id": "rail2", "row": 3, "col": 4, "rowSpan": 1, "colSpan": 1},
            {"id": "rail3", "row": 4, "col": 4, "rowSpan": 1, "colSpan": 1},
            {"id": "rail4", "row": 5, "col": 4, "rowSpan": 1, "colSpan": 1},
        ],
    },
]
